/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bus.station;

import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Yasmin
 */
public class customer extends javax.swing.JFrame {
double cost;
    /**
     * Creates new form customer
     */
    public customer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jrbnonstop = new javax.swing.JRadioButton();
        jrbonestop = new javax.swing.JRadioButton();
        jrbmanystop = new javax.swing.JRadioButton();
        jrbsingle = new javax.swing.JRadioButton();
        jrbround = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jrbeconomy = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jrbcomfort = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jrbbus = new javax.swing.JRadioButton();
        jrbminibus = new javax.swing.JRadioButton();
        jrblimousine = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 204));
        jLabel1.setText("WELCOME");

        buttonGroup2.add(jrbnonstop);
        jrbnonstop.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jrbnonstop.setText("Non-Stop");
        jrbnonstop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbnonstopActionPerformed(evt);
            }
        });

        buttonGroup2.add(jrbonestop);
        jrbonestop.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jrbonestop.setText("One-Stop");
        jrbonestop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbonestopActionPerformed(evt);
            }
        });

        buttonGroup2.add(jrbmanystop);
        jrbmanystop.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jrbmanystop.setText("Many-Stop");
        jrbmanystop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbmanystopActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrbsingle);
        jrbsingle.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jrbsingle.setText("Single");
        jrbsingle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbsingleActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrbround);
        jrbround.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jrbround.setText("Round");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel2.setText("Ticket Type");

        buttonGroup3.add(jrbeconomy);
        jrbeconomy.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jrbeconomy.setText("Economy");
        jrbeconomy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbeconomyActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel3.setText("Trip Type");

        buttonGroup3.add(jrbcomfort);
        jrbcomfort.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jrbcomfort.setText("Comfort");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 204));
        jButton1.setText("Book");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alexandria", "Cairo", "Lybia", "SharmElSheikh", "Ismailia ", " " }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel7.setText("Travelling To");

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setText("Price");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        buttonGroup4.add(jrbbus);
        jrbbus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jrbbus.setText("Bus");
        jrbbus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbbusActionPerformed(evt);
            }
        });

        buttonGroup4.add(jrbminibus);
        jrbminibus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jrbminibus.setText("MiniBus");
        jrbminibus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbminibusActionPerformed(evt);
            }
        });

        buttonGroup4.add(jrblimousine);
        jrblimousine.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jrblimousine.setText("Limousine");
        jrblimousine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrblimousineActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Date");

        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrbnonstop)
                            .addComponent(jLabel7))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jrbonestop)
                                    .addComponent(jLabel2)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 168, Short.MAX_VALUE)
                                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jrbbus, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(jrbminibus, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jButton5)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(66, 66, 66)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jrbmanystop)
                                    .addComponent(jrblimousine, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jrbeconomy)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(jrbsingle)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jrbround)
                                    .addComponent(jrbcomfort))))
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbbus, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jrblimousine, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jrbminibus, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbnonstop)
                    .addComponent(jrbonestop)
                    .addComponent(jrbmanystop))
                .addGap(13, 13, 13)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbround)
                    .addComponent(jrbsingle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jrbeconomy)
                            .addComponent(jrbcomfort))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrbmanystopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbmanystopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbmanystopActionPerformed

    private void jrbonestopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbonestopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbonestopActionPerformed

    private void jrbeconomyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbeconomyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbeconomyActionPerformed

    private void jrbsingleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbsingleActionPerformed
        
    }//GEN-LAST:event_jrbsingleActionPerformed

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        
        
        
    }//GEN-LAST:event_jButton5MouseClicked

    private void jrbnonstopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbnonstopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbnonstopActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
         BusStation k=new BusStation();
         Bus z=new Bus();
         jLabel6.setText(z.Date());
         
         
        try {
            k.Alexandria("Tripss.txt");
            if((jrbbus.isSelected()) &&(jComboBox3.getSelectedItem().equals("Alexandria")) && (jrbnonstop.isSelected()) && (jrbsingle.isSelected()) && jrbeconomy.isSelected()){
                cost=k.Alexandria("Tripss.txt")+55;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            }
            else if ((jrbbus.isSelected()) &&(jComboBox3.getSelectedItem().equals("Alexandria")) && (jrbonestop.isSelected()) && (jrbsingle.isSelected()) && jrbeconomy.isSelected()){
             cost=k.Alexandria("Tripss.txt")+45;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            
            }
            else if((jrbbus.isSelected()) &&(jComboBox3.getSelectedItem().equals("Alexandria")) && (jrbmanystop.isSelected()) && (jrbsingle.isSelected()) && jrbeconomy.isSelected()){
            cost=k.Alexandria("Tripss.txt")+35;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            }
            
            else if((jrbbus.isSelected()) &&(jComboBox3.getSelectedItem().equals("Alexandria")) && (jrbnonstop.isSelected()) && (jrbround.isSelected()) && jrbeconomy.isSelected()){
            cost=k.Alexandria("Tripss.txt")+30;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            }
            else if ((jrbbus.isSelected()) &&(jComboBox3.getSelectedItem().equals("Alexandria")) && (jrbonestop.isSelected()) && (jrbround.isSelected()) && jrbeconomy.isSelected()){
             cost=k.Alexandria("Tripss.txt")+20;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            
            }
            else if ((jrbbus.isSelected()) &&(jComboBox3.getSelectedItem().equals("Alexandria")) && (jrbmanystop.isSelected()) && (jrbround.isSelected()) && jrbeconomy.isSelected()){
             cost=k.Alexandria("Tripss.txt")+5;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            
            }
            
        else     if((jrbbus.isSelected()) &&(jComboBox3.getSelectedItem().equals("Alexandria")) && (jrbnonstop.isSelected()) && (jrbsingle.isSelected()) && jrbeconomy.isSelected()){
                cost=k.Alexandria("Tripss.txt")+55;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            }
            else if ((jrbbus.isSelected()) &&(jComboBox3.getSelectedItem().equals("Alexandria")) && (jrbonestop.isSelected()) && (jrbsingle.isSelected()) && jrbcomfort.isSelected()){
             cost=k.Alexandria("Tripss.txt")+65;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            
            }
            else if((jrbbus.isSelected()) &&(jComboBox3.getSelectedItem().equals("Alexandria")) && (jrbmanystop.isSelected()) && (jrbsingle.isSelected()) && jrbcomfort.isSelected()){
            cost=k.Alexandria("Tripss.txt")+45;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            }
            
            else if((jrbbus.isSelected()) &&(jComboBox3.getSelectedItem().equals("Alexandria")) && (jrbnonstop.isSelected()) && (jrbround.isSelected()) && jrbcomfort.isSelected()){
            cost=k.Alexandria("Tripss.txt")+40;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            }
            else if ((jrbbus.isSelected()) &&(jComboBox3.getSelectedItem().equals("Alexandria")) && (jrbonestop.isSelected()) && (jrbround.isSelected()) && jrbcomfort.isSelected()){
             cost=k.Alexandria("Tripss.txt")+30;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            
            }
            else if ((jrbbus.isSelected()) &&(jComboBox3.getSelectedItem().equals("Alexandria")) && (jrbmanystop.isSelected()) && (jrbround.isSelected()) && jrbcomfort.isSelected()){
             cost=k.Alexandria("Tripss.txt")+20;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            
            }
            
        } catch (IOException ex) {
            Logger.getLogger(customer.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            k.Cairo("Tripss.txt");
            if((jrbbus.isSelected()) &&(jComboBox3.getSelectedItem().equals("Cairo")) && (jrbnonstop.isSelected()) && (jrbsingle.isSelected()) && jrbeconomy.isSelected()){
                cost=k.Cairo("Tripss.txt")+55;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            }
            else if ((jrbbus.isSelected()) &&(jComboBox3.getSelectedItem().equals("Cairo")) && (jrbonestop.isSelected()) && (jrbsingle.isSelected()) && jrbeconomy.isSelected()){
             cost=k.Cairo("Tripss.txt")+45;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            
            }
            else if((jrbbus.isSelected()) &&(jComboBox3.getSelectedItem().equals("Cairo")) && (jrbmanystop.isSelected()) && (jrbsingle.isSelected()) && jrbeconomy.isSelected()){
            cost=k.Cairo("Tripss.txt")+35;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            }
            
            else if((jrbbus.isSelected()) &&(jComboBox3.getSelectedItem().equals("Cairo")) && (jrbnonstop.isSelected()) && (jrbround.isSelected()) && jrbeconomy.isSelected()){
            cost=k.Cairo("Tripss.txt")+30;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            }
            else if ((jrbbus.isSelected()) &&(jComboBox3.getSelectedItem().equals("Cairo")) && (jrbonestop.isSelected()) && (jrbround.isSelected()) && jrbeconomy.isSelected()){
             cost=k.Cairo("Tripss.txt")+20;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            
            }
            else if ((jrbbus.isSelected()) &&(jComboBox3.getSelectedItem().equals("Cairo")) && (jrbmanystop.isSelected()) && (jrbround.isSelected()) && jrbeconomy.isSelected()){
             cost=k.Cairo("Tripss.txt")+5;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            
            }
            
       else      if((jrbbus.isSelected()) &&(jComboBox3.getSelectedItem().equals("Cairo")) && (jrbnonstop.isSelected()) && (jrbsingle.isSelected()) && jrbeconomy.isSelected()){
                cost=k.Cairo("Tripss.txt")+55;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            }
            else if ((jrbbus.isSelected()) &&(jComboBox3.getSelectedItem().equals("Cairo")) && (jrbonestop.isSelected()) && (jrbsingle.isSelected()) && jrbcomfort.isSelected()){
             cost=k.Cairo("Tripss.txt")+65;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            
            }
            else if((jrbbus.isSelected()) &&(jComboBox3.getSelectedItem().equals("Cairo")) && (jrbmanystop.isSelected()) && (jrbsingle.isSelected()) && jrbcomfort.isSelected()){
            cost=k.Cairo("Tripss.txt")+45;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            }
            
            else if((jrbbus.isSelected()) &&(jComboBox3.getSelectedItem().equals("Cairo")) && (jrbnonstop.isSelected()) && (jrbround.isSelected()) && jrbcomfort.isSelected()){
            cost=k.Cairo("Tripss.txt")+40;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            }
            else if ((jrbbus.isSelected()) &&(jComboBox3.getSelectedItem().equals("Cairo")) && (jrbonestop.isSelected()) && (jrbround.isSelected()) && jrbcomfort.isSelected()){
             cost=k.Cairo("Tripss.txt")+30;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            
            }
            else if ((jrbbus.isSelected()) &&(jComboBox3.getSelectedItem().equals("Cairo")) && (jrbmanystop.isSelected()) && (jrbround.isSelected()) && jrbcomfort.isSelected()){
             cost=k.Cairo("Tripss.txt")+20;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            
            }
            
        } catch (IOException ex) {
            Logger.getLogger(customer.class.getName()).log(Level.SEVERE, null, ex);
            ex.printStackTrace();
        }
        try {
            k.Lybia("Tripss.txt");
            if((jrbbus.isSelected()) &&(jComboBox3.getSelectedItem().equals("Lybia")) && (jrbnonstop.isSelected()) && (jrbsingle.isSelected()) && jrbeconomy.isSelected()){
                cost=k.Lybia("Tripss.txt")+55;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            }
            else if ((jrbbus.isSelected()) &&(jComboBox3.getSelectedItem().equals("Lybia")) && (jrbonestop.isSelected()) && (jrbsingle.isSelected()) && jrbeconomy.isSelected()){
             cost=k.Lybia("Tripss.txt")+45;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            
            }
            else if((jrbbus.isSelected()) &&(jComboBox3.getSelectedItem().equals("Lybia")) && (jrbmanystop.isSelected()) && (jrbsingle.isSelected()) && jrbeconomy.isSelected()){
            cost=k.Lybia("Tripss.txt")+35;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            }
            
            else if((jrbbus.isSelected()) &&(jComboBox3.getSelectedItem().equals("Lybia")) && (jrbnonstop.isSelected()) && (jrbround.isSelected()) && jrbeconomy.isSelected()){
            cost=k.Lybia("Tripss.txt")+30;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            }
            else if ((jrbbus.isSelected()) &&(jComboBox3.getSelectedItem().equals("Lybia")) && (jrbonestop.isSelected()) && (jrbround.isSelected()) && jrbeconomy.isSelected()){
             cost=k.Lybia("Tripss.txt")+20;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            
            }
            else if ((jrbbus.isSelected()) &&(jComboBox3.getSelectedItem().equals("Lybia")) && (jrbmanystop.isSelected()) && (jrbround.isSelected()) && jrbeconomy.isSelected()){
             cost=k.Lybia("Tripss.txt")+5;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            
            }
            
           else  if((jrbbus.isSelected()) &&(jComboBox3.getSelectedItem().equals("Lybia")) && (jrbnonstop.isSelected()) && (jrbsingle.isSelected()) && jrbeconomy.isSelected()){
                cost=k.Lybia("Tripss.txt")+55;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            }
            else if ((jrbbus.isSelected()) &&(jComboBox3.getSelectedItem().equals("Lybia")) && (jrbonestop.isSelected()) && (jrbsingle.isSelected()) && jrbcomfort.isSelected()){
             cost=k.Lybia("Tripss.txt")+65;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            
            }
            else if((jrbbus.isSelected()) &&(jComboBox3.getSelectedItem().equals("Lybia")) && (jrbmanystop.isSelected()) && (jrbsingle.isSelected()) && jrbcomfort.isSelected()){
            cost=k.Lybia("Tripss.txt")+45;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            }
            
            else if((jrbbus.isSelected()) &&(jComboBox3.getSelectedItem().equals("Lybia")) && (jrbnonstop.isSelected()) && (jrbround.isSelected()) && jrbcomfort.isSelected()){
            cost=k.Lybia("Tripss.txt")+40;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            }
            else if ((jrbbus.isSelected()) &&(jComboBox3.getSelectedItem().equals("Lybia")) && (jrbonestop.isSelected()) && (jrbround.isSelected()) && jrbcomfort.isSelected()){
             cost=k.Lybia("Tripss.txt")+30;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            
            }
            else if ((jrbbus.isSelected()) &&(jComboBox3.getSelectedItem().equals("Lybia")) && (jrbmanystop.isSelected()) && (jrbround.isSelected()) && jrbcomfort.isSelected()){
             cost=k.Lybia("Tripss.txt")+20;
                String sCost=String.format(" Egp%.2f " , cost);
                jLabel4.setText(sCost);
            
            }
            
        } catch (IOException ex) {
            Logger.getLogger(customer.class.getName()).log(Level.SEVERE, null, ex);
        }
                    try {
            k.Sharm("Tripss.txt");
            if((jrbbus.isSelected()) &&(jComboBox3.getSelectedItem().equals("SharmElSheikh")) && (jrbnonstop.isSelected()) && (jrbsingle.isSelected()) && jrbeconomy.isSelected()){
                cost=k.Sharm("Tripss.txt")+55;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            }
            else if ((jrbbus.isSelected()) &&(jComboBox3.getSelectedItem().equals("SharmElSheikh")) && (jrbonestop.isSelected()) && (jrbsingle.isSelected()) && jrbeconomy.isSelected()){
             cost=k.Sharm("Tripss.txt")+45;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            
            }
            else if((jrbbus.isSelected()) &&(jComboBox3.getSelectedItem().equals("SharmElSheikh")) && (jrbmanystop.isSelected()) && (jrbsingle.isSelected()) && jrbeconomy.isSelected()){
            cost=k.Sharm("Tripss.txt")+35;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            }
            
            else if((jrbbus.isSelected()) &&(jComboBox3.getSelectedItem().equals("SharmElSheikh")) && (jrbnonstop.isSelected()) && (jrbround.isSelected()) && jrbeconomy.isSelected()){
            cost=k.Sharm("Tripss.txt")+30;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            }
            else if ((jrbbus.isSelected()) &&(jComboBox3.getSelectedItem().equals("SharmElSheikh")) && (jrbonestop.isSelected()) && (jrbround.isSelected()) && jrbeconomy.isSelected()){
             cost=k.Sharm("Tripss.txt")+20;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            
            }
            else if ((jrbbus.isSelected()) &&(jComboBox3.getSelectedItem().equals("SharmElSheikh")) && (jrbmanystop.isSelected()) && (jrbround.isSelected()) && jrbeconomy.isSelected()){
             cost=k.Sharm("Tripss.txt")+5;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            
            }
            
           else  if((jrbbus.isSelected()) &&(jComboBox3.getSelectedItem().equals("SharmElSheikh")) && (jrbnonstop.isSelected()) && (jrbsingle.isSelected()) && jrbeconomy.isSelected()){
                cost=k.Sharm("Tripss.txt")+55;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            }
            else if ((jrbbus.isSelected()) &&(jComboBox3.getSelectedItem().equals("SharmElSheikh")) && (jrbonestop.isSelected()) && (jrbsingle.isSelected()) && jrbcomfort.isSelected()){
             cost=k.Sharm("Tripss.txt")+65;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            
            }
            else if((jrbbus.isSelected()) &&(jComboBox3.getSelectedItem().equals("SharmElSheikh")) && (jrbmanystop.isSelected()) && (jrbsingle.isSelected()) && jrbcomfort.isSelected()){
            cost=k.Sharm("Tripss.txt")+45;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            }
            
            else if((jrbbus.isSelected()) &&(jComboBox3.getSelectedItem().equals("SharmElSheikh")) && (jrbnonstop.isSelected()) && (jrbround.isSelected()) && jrbcomfort.isSelected()){
            cost=k.Sharm("Tripss.txt")+40;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            }
            else if ((jrbbus.isSelected()) &&(jComboBox3.getSelectedItem().equals("SharmElSheikh")) && (jrbonestop.isSelected()) && (jrbround.isSelected()) && jrbcomfort.isSelected()){
             cost=k.Sharm("Tripss.txt")+30;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            
            }
            else if ((jrbbus.isSelected()) &&(jComboBox3.getSelectedItem().equals("SharmElSheikh")) && (jrbmanystop.isSelected()) && (jrbround.isSelected()) && jrbcomfort.isSelected()){
             cost=k.Sharm("Tripss.txt")+20;
                String sCost=String.format(" Egp%.2f " , cost);
                jLabel4.setText(sCost);
            
            }
            
        } catch (IOException ex) {
            Logger.getLogger(customer.class.getName()).log(Level.SEVERE, null, ex);
        }
                    
                    try {
            k.Ismailia("Tripss.txt");
            if((jrbbus.isSelected()) &&(jComboBox3.getSelectedItem().equals("Ismailia")) && (jrbnonstop.isSelected()) && (jrbsingle.isSelected()) && jrbeconomy.isSelected()){
                cost=k.Ismailia("Tripss.txt")+55;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            }
            else if ((jrbbus.isSelected()) &&(jComboBox3.getSelectedItem().equals("Ismailia")) && (jrbonestop.isSelected()) && (jrbsingle.isSelected()) && jrbeconomy.isSelected()){
             cost=k.Ismailia("Tripss.txt")+45;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            
            }
            else if((jrbbus.isSelected()) &&(jComboBox3.getSelectedItem().equals("Ismailia")) && (jrbmanystop.isSelected()) && (jrbsingle.isSelected()) && jrbeconomy.isSelected()){
            cost=k.Ismailia("Tripss.txt")+35;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            }
            
            else if((jrbbus.isSelected()) &&(jComboBox3.getSelectedItem().equals("Ismailia")) && (jrbnonstop.isSelected()) && (jrbround.isSelected()) && jrbeconomy.isSelected()){
            cost=k.Ismailia("Tripss.txt")+30;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            }
            else if ((jrbbus.isSelected()) &&(jComboBox3.getSelectedItem().equals("Ismailia")) && (jrbonestop.isSelected()) && (jrbround.isSelected()) && jrbeconomy.isSelected()){
             cost=k.Ismailia("Tripss.txt")+20;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            
            }
            else if ((jrbbus.isSelected()) &&(jComboBox3.getSelectedItem().equals("Ismailia")) && (jrbmanystop.isSelected()) && (jrbround.isSelected()) && jrbeconomy.isSelected()){
             cost=k.Ismailia("Tripss.txt")+5;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            
            }
            
           else  if((jrbbus.isSelected()) &&(jComboBox3.getSelectedItem().equals("Ismailia")) && (jrbnonstop.isSelected()) && (jrbsingle.isSelected()) && jrbeconomy.isSelected()){
                cost=k.Ismailia("Tripss.txt")+55;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            }
            else if ((jrbbus.isSelected()) &&(jComboBox3.getSelectedItem().equals("Ismailia")) && (jrbonestop.isSelected()) && (jrbsingle.isSelected()) && jrbcomfort.isSelected()){
             cost=k.Ismailia("Tripss.txt")+65;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            
            }
            else if((jrbbus.isSelected()) &&(jComboBox3.getSelectedItem().equals("Ismailia")) && (jrbmanystop.isSelected()) && (jrbsingle.isSelected()) && jrbcomfort.isSelected()){
            cost=k.Ismailia("Tripss.txt")+45;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            }
            
            else if((jrbbus.isSelected()) &&(jComboBox3.getSelectedItem().equals("Ismailia")) && (jrbnonstop.isSelected()) && (jrbround.isSelected()) && jrbcomfort.isSelected()){
            cost=k.Ismailia("Tripss.txt")+40;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            }
            else if ((jrbbus.isSelected()) &&(jComboBox3.getSelectedItem().equals("Ismailia")) && (jrbonestop.isSelected()) && (jrbround.isSelected()) && jrbcomfort.isSelected()){
             cost=k.Ismailia("Tripss.txt")+30;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            
            }
            else if ((jrbbus.isSelected()) &&(jComboBox3.getSelectedItem().equals("Ismailia")) && (jrbmanystop.isSelected()) && (jrbround.isSelected()) && jrbcomfort.isSelected()){
             cost=k.Ismailia("Tripss.txt")+20;
                String sCost=String.format(" Egp%.2f " , cost);
                jLabel4.setText(sCost);
            
            }
            
        } catch (IOException ex) {
            Logger.getLogger(customer.class.getName()).log(Level.SEVERE, null, ex);
        }
                    //limousine//
                    
                      try {
            k.Alexandria("Tripss.txt");
            if((jrblimousine.isSelected()) &&(jComboBox3.getSelectedItem().equals("Alexandria")) && (jrbnonstop.isSelected()) && (jrbsingle.isSelected()) && jrbeconomy.isSelected()){
                cost=k.Alexandria("Tripss.txt")+105;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            }
            else if ((jrblimousine.isSelected()) &&(jComboBox3.getSelectedItem().equals("Alexandria")) && (jrbonestop.isSelected()) && (jrbsingle.isSelected()) && jrbeconomy.isSelected()){
             cost=k.Alexandria("Tripss.txt")+95;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            
            }
            else if((jrblimousine.isSelected()) &&(jComboBox3.getSelectedItem().equals("Alexandria")) && (jrbmanystop.isSelected()) && (jrbsingle.isSelected()) && jrbeconomy.isSelected()){
            cost=k.Alexandria("Tripss.txt")+85;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            }
            
            else if((jrblimousine.isSelected()) &&(jComboBox3.getSelectedItem().equals("Alexandria")) && (jrbnonstop.isSelected()) && (jrbround.isSelected()) && jrbeconomy.isSelected()){
            cost=k.Alexandria("Tripss.txt")+80;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            }
            else if ((jrblimousine.isSelected()) &&(jComboBox3.getSelectedItem().equals("Alexandria")) && (jrbonestop.isSelected()) && (jrbround.isSelected()) && jrbeconomy.isSelected()){
             cost=k.Alexandria("Tripss.txt")+70;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            
            }
            else if ((jrblimousine.isSelected()) &&(jComboBox3.getSelectedItem().equals("Alexandria")) && (jrbmanystop.isSelected()) && (jrbround.isSelected()) && jrbeconomy.isSelected()){
             cost=k.Alexandria("Tripss.txt")+55;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            
            }
            
        else  if((jrblimousine.isSelected()) &&(jComboBox3.getSelectedItem().equals("Alexandria")) && (jrbnonstop.isSelected()) && (jrbsingle.isSelected()) && jrbeconomy.isSelected()){
                cost=k.Alexandria("Tripss.txt")+105;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            }
            else if ((jrblimousine.isSelected()) &&(jComboBox3.getSelectedItem().equals("Alexandria")) && (jrbonestop.isSelected()) && (jrbsingle.isSelected()) && jrbcomfort.isSelected()){
             cost=k.Alexandria("Tripss.txt")+115;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            
            }
            else if((jrblimousine.isSelected()) &&(jComboBox3.getSelectedItem().equals("Alexandria")) && (jrbmanystop.isSelected()) && (jrbsingle.isSelected()) && jrbcomfort.isSelected()){
            cost=k.Alexandria("Tripss.txt")+95;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            }
            
            else if((jrblimousine.isSelected()) &&(jComboBox3.getSelectedItem().equals("Alexandria")) && (jrbnonstop.isSelected()) && (jrbround.isSelected()) && jrbcomfort.isSelected()){
            cost=k.Alexandria("Tripss.txt")+90;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            }
            else if ((jrblimousine.isSelected()) &&(jComboBox3.getSelectedItem().equals("Alexandria")) && (jrbonestop.isSelected()) && (jrbround.isSelected()) && jrbcomfort.isSelected()){
             cost=k.Alexandria("Tripss.txt")+80;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            
            }
            else if ((jrblimousine.isSelected()) &&(jComboBox3.getSelectedItem().equals("Alexandria")) && (jrbmanystop.isSelected()) && (jrbround.isSelected()) && jrbcomfort.isSelected()){
             cost=k.Alexandria("Tripss.txt")+70;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            
            }
            
        } catch (IOException ex) {
            Logger.getLogger(customer.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            k.Cairo("Tripss.txt");
            if((jrblimousine.isSelected()) &&(jComboBox3.getSelectedItem().equals("Cairo")) && (jrbnonstop.isSelected()) && (jrbsingle.isSelected()) && jrbeconomy.isSelected()){
                cost=k.Cairo("Tripss.txt")+105;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            }
            else if ((jrblimousine.isSelected()) &&(jComboBox3.getSelectedItem().equals("Cairo")) && (jrbonestop.isSelected()) && (jrbsingle.isSelected()) && jrbeconomy.isSelected()){
             cost=k.Cairo("Tripss.txt")+95;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            
            }
            else if((jrblimousine.isSelected()) &&(jComboBox3.getSelectedItem().equals("Cairo")) && (jrbmanystop.isSelected()) && (jrbsingle.isSelected()) && jrbeconomy.isSelected()){
            cost=k.Cairo("Tripss.txt")+85;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            }
            
            else if((jrblimousine.isSelected()) &&(jComboBox3.getSelectedItem().equals("Cairo")) && (jrbnonstop.isSelected()) && (jrbround.isSelected()) && jrbeconomy.isSelected()){
            cost=k.Cairo("Tripss.txt")+80;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            }
            else if ((jrblimousine.isSelected()) &&(jComboBox3.getSelectedItem().equals("Cairo")) && (jrbonestop.isSelected()) && (jrbround.isSelected()) && jrbeconomy.isSelected()){
             cost=k.Cairo("Tripss.txt")+70;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            
            }
            else if ((jrblimousine.isSelected()) &&(jComboBox3.getSelectedItem().equals("Cairo")) && (jrbmanystop.isSelected()) && (jrbround.isSelected()) && jrbeconomy.isSelected()){
             cost=k.Cairo("Tripss.txt")+55;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            
            }
            
       else      if((jrblimousine.isSelected()) &&(jComboBox3.getSelectedItem().equals("Cairo")) && (jrbnonstop.isSelected()) && (jrbsingle.isSelected()) && jrbeconomy.isSelected()){
                cost=k.Cairo("Tripss.txt")+105;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            }
            else if ((jrblimousine.isSelected()) &&(jComboBox3.getSelectedItem().equals("Cairo")) && (jrbonestop.isSelected()) && (jrbsingle.isSelected()) && jrbcomfort.isSelected()){
             cost=k.Cairo("Tripss.txt")+115;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            
            }
            else if((jrblimousine.isSelected()) &&(jComboBox3.getSelectedItem().equals("Cairo")) && (jrbmanystop.isSelected()) && (jrbsingle.isSelected()) && jrbcomfort.isSelected()){
            cost=k.Cairo("Tripss.txt")+95;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            }
            
            else if((jrblimousine.isSelected()) &&(jComboBox3.getSelectedItem().equals("Cairo")) && (jrbnonstop.isSelected()) && (jrbround.isSelected()) && jrbcomfort.isSelected()){
            cost=k.Cairo("Tripss.txt")+90;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            }
            else if ((jrblimousine.isSelected()) &&(jComboBox3.getSelectedItem().equals("Cairo")) && (jrbonestop.isSelected()) && (jrbround.isSelected()) && jrbcomfort.isSelected()){
             cost=k.Cairo("Tripss.txt")+80;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            
            }
            else if ((jrblimousine.isSelected()) &&(jComboBox3.getSelectedItem().equals("Cairo")) && (jrbmanystop.isSelected()) && (jrbround.isSelected()) && jrbcomfort.isSelected()){
             cost=k.Cairo("Tripss.txt")+70;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            
            }
            
        } catch (IOException ex) {
            Logger.getLogger(customer.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            k.Lybia("Tripss.txt");
            if((jrblimousine.isSelected()) &&(jComboBox3.getSelectedItem().equals("Lybia")) && (jrbnonstop.isSelected()) && (jrbsingle.isSelected()) && jrbeconomy.isSelected()){
                cost=k.Lybia("Tripss.txt")+105;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            }
            else if ((jrblimousine.isSelected()) &&(jComboBox3.getSelectedItem().equals("Lybia")) && (jrbonestop.isSelected()) && (jrbsingle.isSelected()) && jrbeconomy.isSelected()){
             cost=k.Lybia("Tripss.txt")+95;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            
            }
            else if((jrblimousine.isSelected()) &&(jComboBox3.getSelectedItem().equals("Lybia")) && (jrbmanystop.isSelected()) && (jrbsingle.isSelected()) && jrbeconomy.isSelected()){
            cost=k.Lybia("Tripss.txt")+85;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            }
            
            else if((jrblimousine.isSelected()) &&(jComboBox3.getSelectedItem().equals("Lybia")) && (jrbnonstop.isSelected()) && (jrbround.isSelected()) && jrbeconomy.isSelected()){
            cost=k.Lybia("Tripss.txt")+80;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            }
            else if ((jrblimousine.isSelected()) &&(jComboBox3.getSelectedItem().equals("Lybia")) && (jrbonestop.isSelected()) && (jrbround.isSelected()) && jrbeconomy.isSelected()){
             cost=k.Lybia("Tripss.txt")+70;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            
            }
            else if ((jrblimousine.isSelected()) &&(jComboBox3.getSelectedItem().equals("Lybia")) && (jrbmanystop.isSelected()) && (jrbround.isSelected()) && jrbeconomy.isSelected()){
             cost=k.Lybia("Tripss.txt")+55;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            
            }
            
           else  if((jrblimousine.isSelected()) &&(jComboBox3.getSelectedItem().equals("Lybia")) && (jrbnonstop.isSelected()) && (jrbsingle.isSelected()) && jrbeconomy.isSelected()){
                cost=k.Lybia("Tripss.txt")+105;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            }
            else if ((jrblimousine.isSelected()) &&(jComboBox3.getSelectedItem().equals("Lybia")) && (jrbonestop.isSelected()) && (jrbsingle.isSelected()) && jrbcomfort.isSelected()){
             cost=k.Lybia("Tripss.txt")+115;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            
            }
            else if((jrblimousine.isSelected()) &&(jComboBox3.getSelectedItem().equals("Lybia")) && (jrbmanystop.isSelected()) && (jrbsingle.isSelected()) && jrbcomfort.isSelected()){
            cost=k.Lybia("Tripss.txt")+95;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            }
            
            else if((jrblimousine.isSelected()) &&(jComboBox3.getSelectedItem().equals("Lybia")) && (jrbnonstop.isSelected()) && (jrbround.isSelected()) && jrbcomfort.isSelected()){
            cost=k.Lybia("Tripss.txt")+90;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            }
            else if ((jrblimousine.isSelected()) &&(jComboBox3.getSelectedItem().equals("Lybia")) && (jrbonestop.isSelected()) && (jrbround.isSelected()) && jrbcomfort.isSelected()){
             cost=k.Lybia("Tripss.txt")+80;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            
            }
            else if ((jrblimousine.isSelected()) &&(jComboBox3.getSelectedItem().equals("Lybia")) && (jrbmanystop.isSelected()) && (jrbround.isSelected()) && jrbcomfort.isSelected()){
             cost=k.Lybia("Tripss.txt")+70;
                String sCost=String.format(" Egp%.2f " , cost);
                jLabel4.setText(sCost);
            
            }
            
        } catch (IOException ex) {
            Logger.getLogger(customer.class.getName()).log(Level.SEVERE, null, ex);
        }
                    try {
            k.Sharm("Tripss.txt");
            if((jrblimousine.isSelected()) &&(jComboBox3.getSelectedItem().equals("SharmElSheikh")) && (jrbnonstop.isSelected()) && (jrbsingle.isSelected()) && jrbeconomy.isSelected()){
                cost=k.Sharm("Tripss.txt")+105;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            }
            else if ((jrblimousine.isSelected()) &&(jComboBox3.getSelectedItem().equals("SharmElSheikh")) && (jrbonestop.isSelected()) && (jrbsingle.isSelected()) && jrbeconomy.isSelected()){
             cost=k.Sharm("Tripss.txt")+95;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            
            }
            else if((jrblimousine.isSelected()) &&(jComboBox3.getSelectedItem().equals("SharmElSheikh")) && (jrbmanystop.isSelected()) && (jrbsingle.isSelected()) && jrbeconomy.isSelected()){
            cost=k.Sharm("Tripss.txt")+85;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            }
            
            else if((jrblimousine.isSelected()) &&(jComboBox3.getSelectedItem().equals("SharmElSheikh")) && (jrbnonstop.isSelected()) && (jrbround.isSelected()) && jrbeconomy.isSelected()){
            cost=k.Sharm("Tripss.txt")+80;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            }
            else if ((jrblimousine.isSelected()) &&(jComboBox3.getSelectedItem().equals("SharmElSheikh")) && (jrbonestop.isSelected()) && (jrbround.isSelected()) && jrbeconomy.isSelected()){
             cost=k.Sharm("Tripss.txt")+70;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            
            }
            else if ((jrblimousine.isSelected()) &&(jComboBox3.getSelectedItem().equals("SharmElSheikh")) && (jrbmanystop.isSelected()) && (jrbround.isSelected()) && jrbeconomy.isSelected()){
             cost=k.Sharm("Tripss.txt")+55;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            
            }
            
           else  if((jrblimousine.isSelected()) &&(jComboBox3.getSelectedItem().equals("SharmElSheikh")) && (jrbnonstop.isSelected()) && (jrbsingle.isSelected()) && jrbeconomy.isSelected()){
                cost=k.Sharm("Tripss.txt")+105;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            }
            else if ((jrblimousine.isSelected()) &&(jComboBox3.getSelectedItem().equals("SharmElSheikh")) && (jrbonestop.isSelected()) && (jrbsingle.isSelected()) && jrbcomfort.isSelected()){
             cost=k.Sharm("Tripss.txt")+115;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            
            }
            else if((jrblimousine.isSelected()) &&(jComboBox3.getSelectedItem().equals("SharmElSheikh")) && (jrbmanystop.isSelected()) && (jrbsingle.isSelected()) && jrbcomfort.isSelected()){
            cost=k.Sharm("Tripss.txt")+95;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            }
            
            else if((jrblimousine.isSelected()) &&(jComboBox3.getSelectedItem().equals("SharmElSheikh")) && (jrbnonstop.isSelected()) && (jrbround.isSelected()) && jrbcomfort.isSelected()){
            cost=k.Sharm("Tripss.txt")+90;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            }
            else if ((jrblimousine.isSelected()) &&(jComboBox3.getSelectedItem().equals("SharmElSheikh")) && (jrbonestop.isSelected()) && (jrbround.isSelected()) && jrbcomfort.isSelected()){
             cost=k.Sharm("Tripss.txt")+80;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            
            }
            else if ((jrblimousine.isSelected()) &&(jComboBox3.getSelectedItem().equals("SharmElSheikh")) && (jrbmanystop.isSelected()) && (jrbround.isSelected()) && jrbcomfort.isSelected()){
             cost=k.Sharm("Tripss.txt")+70;
                String sCost=String.format(" Egp%.2f " , cost);
                jLabel4.setText(sCost);
            
            }
            
        } catch (IOException ex) {
            Logger.getLogger(customer.class.getName()).log(Level.SEVERE, null, ex);
        }
                    
                    try {
            k.Ismailia("Tripss.txt");
            if((jrblimousine.isSelected()) &&(jComboBox3.getSelectedItem().equals("Ismailia")) && (jrbnonstop.isSelected()) && (jrbsingle.isSelected()) && jrbeconomy.isSelected()){
                cost=k.Ismailia("Tripss.txt")+105;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            }
            else if ((jrblimousine.isSelected()) &&(jComboBox3.getSelectedItem().equals("Ismailia")) && (jrbonestop.isSelected()) && (jrbsingle.isSelected()) && jrbeconomy.isSelected()){
             cost=k.Ismailia("Tripss.txt")+95;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            
            }
            else if((jrblimousine.isSelected()) &&(jComboBox3.getSelectedItem().equals("Ismailia")) && (jrbmanystop.isSelected()) && (jrbsingle.isSelected()) && jrbeconomy.isSelected()){
            cost=k.Ismailia("Tripss.txt")+85;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            }
            
            else if((jrblimousine.isSelected()) &&(jComboBox3.getSelectedItem().equals("Ismailia")) && (jrbnonstop.isSelected()) && (jrbround.isSelected()) && jrbeconomy.isSelected()){
            cost=k.Ismailia("Tripss.txt")+80;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            }
            else if ((jrblimousine.isSelected()) &&(jComboBox3.getSelectedItem().equals("Ismailia")) && (jrbonestop.isSelected()) && (jrbround.isSelected()) && jrbeconomy.isSelected()){
             cost=k.Ismailia("Tripss.txt")+70;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            
            }
            else if ((jrblimousine.isSelected()) &&(jComboBox3.getSelectedItem().equals("Ismailia")) && (jrbmanystop.isSelected()) && (jrbround.isSelected()) && jrbeconomy.isSelected()){
             cost=k.Ismailia("Tripss.txt")+55;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            
            }
            
           else  if((jrblimousine.isSelected()) &&(jComboBox3.getSelectedItem().equals("Ismailia")) && (jrbnonstop.isSelected()) && (jrbsingle.isSelected()) && jrbeconomy.isSelected()){
                cost=k.Ismailia("Tripss.txt")+105;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            }
            else if ((jrblimousine.isSelected()) &&(jComboBox3.getSelectedItem().equals("Ismailia")) && (jrbonestop.isSelected()) && (jrbsingle.isSelected()) && jrbcomfort.isSelected()){
             cost=k.Ismailia("Tripss.txt")+115;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            
            }
            else if((jrblimousine.isSelected()) &&(jComboBox3.getSelectedItem().equals("Ismailia")) && (jrbmanystop.isSelected()) && (jrbsingle.isSelected()) && jrbcomfort.isSelected()){
            cost=k.Ismailia("Tripss.txt")+95;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            }
            
            else if((jrblimousine.isSelected()) &&(jComboBox3.getSelectedItem().equals("Ismailia")) && (jrbnonstop.isSelected()) && (jrbround.isSelected()) && jrbcomfort.isSelected()){
            cost=k.Ismailia("Tripss.txt")+90;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            }
            else if ((jrblimousine.isSelected()) &&(jComboBox3.getSelectedItem().equals("Ismailia")) && (jrbonestop.isSelected()) && (jrbround.isSelected()) && jrbcomfort.isSelected()){
             cost=k.Ismailia("Tripss.txt")+80;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            
            }
            else if ((jrblimousine.isSelected()) &&(jComboBox3.getSelectedItem().equals("Ismailia")) && (jrbmanystop.isSelected()) && (jrbround.isSelected()) && jrbcomfort.isSelected()){
             cost=k.Ismailia("Tripss.txt")+70;
                String sCost=String.format(" Egp%.2f " , cost);
                jLabel4.setText(sCost);
            
            }
            
        } catch (IOException ex) {
            Logger.getLogger(customer.class.getName()).log(Level.SEVERE, null, ex);
        }
                    
                    //minibus
                      try {
            k.Alexandria("Tripss.txt");
            if((jrbminibus.isSelected()) &&(jComboBox3.getSelectedItem().equals("Alexandria")) && (jrbnonstop.isSelected()) && (jrbsingle.isSelected()) && jrbeconomy.isSelected()){
                cost=k.Alexandria("Tripss.txt")+55;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            }
            else if ((jrbminibus.isSelected()) &&(jComboBox3.getSelectedItem().equals("Alexandria")) && (jrbonestop.isSelected()) && (jrbsingle.isSelected()) && jrbeconomy.isSelected()){
             cost=k.Alexandria("Tripss.txt")+45;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            
            }
            else if((jrbminibus.isSelected()) &&(jComboBox3.getSelectedItem().equals("Alexandria")) && (jrbmanystop.isSelected()) && (jrbsingle.isSelected()) && jrbeconomy.isSelected()){
            cost=k.Alexandria("Tripss.txt")+35;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            }
            
            else if((jrbminibus.isSelected()) &&(jComboBox3.getSelectedItem().equals("Alexandria")) && (jrbnonstop.isSelected()) && (jrbround.isSelected()) && jrbeconomy.isSelected()){
            cost=k.Alexandria("Tripss.txt")+30;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            }
            else if ((jrbminibus.isSelected()) &&(jComboBox3.getSelectedItem().equals("Alexandria")) && (jrbonestop.isSelected()) && (jrbround.isSelected()) && jrbeconomy.isSelected()){
             cost=k.Alexandria("Tripss.txt")+20;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            
            }
            else if ((jrbminibus.isSelected()) &&(jComboBox3.getSelectedItem().equals("Alexandria")) && (jrbmanystop.isSelected()) && (jrbround.isSelected()) && jrbeconomy.isSelected()){
             cost=k.Alexandria("Tripss.txt")+5;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            
            }
            
        else     if((jrbminibus.isSelected()) &&(jComboBox3.getSelectedItem().equals("Alexandria")) && (jrbnonstop.isSelected()) && (jrbsingle.isSelected()) && jrbeconomy.isSelected()){
                cost=k.Alexandria("Tripss.txt")+55;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            }
            else if ((jrbminibus.isSelected()) &&(jComboBox3.getSelectedItem().equals("Alexandria")) && (jrbonestop.isSelected()) && (jrbsingle.isSelected()) && jrbcomfort.isSelected()){
             cost=k.Alexandria("Tripss.txt")+65;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            
            }
            else if((jrbminibus.isSelected()) &&(jComboBox3.getSelectedItem().equals("Alexandria")) && (jrbmanystop.isSelected()) && (jrbsingle.isSelected()) && jrbcomfort.isSelected()){
            cost=k.Alexandria("Tripss.txt")+45;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            }
            
            else if((jrbminibus.isSelected()) &&(jComboBox3.getSelectedItem().equals("Alexandria")) && (jrbnonstop.isSelected()) && (jrbround.isSelected()) && jrbcomfort.isSelected()){
            cost=k.Alexandria("Tripss.txt")+40;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            }
            else if ((jrbminibus.isSelected()) &&(jComboBox3.getSelectedItem().equals("Alexandria")) && (jrbonestop.isSelected()) && (jrbround.isSelected()) && jrbcomfort.isSelected()){
             cost=k.Alexandria("Tripss.txt")+30;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            
            }
            else if ((jrbminibus.isSelected()) &&(jComboBox3.getSelectedItem().equals("Alexandria")) && (jrbmanystop.isSelected()) && (jrbround.isSelected()) && jrbcomfort.isSelected()){
             cost=k.Alexandria("Tripss.txt")+20;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            
            }
            
        } catch (IOException ex) {
            Logger.getLogger(customer.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            k.Cairo("Tripss.txt");
            if((jrbminibus.isSelected()) &&(jComboBox3.getSelectedItem().equals("Cairo")) && (jrbnonstop.isSelected()) && (jrbsingle.isSelected()) && jrbeconomy.isSelected()){
                cost=k.Cairo("Tripss.txt")+55;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            }
            else if ((jrbminibus.isSelected()) &&(jComboBox3.getSelectedItem().equals("Cairo")) && (jrbonestop.isSelected()) && (jrbsingle.isSelected()) && jrbeconomy.isSelected()){
             cost=k.Cairo("Tripss.txt")+45;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            
            }
            else if((jrbminibus.isSelected()) &&(jComboBox3.getSelectedItem().equals("Cairo")) && (jrbmanystop.isSelected()) && (jrbsingle.isSelected()) && jrbeconomy.isSelected()){
            cost=k.Cairo("Tripss.txt")+35;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            }
            
            else if((jrbminibus.isSelected()) &&(jComboBox3.getSelectedItem().equals("Cairo")) && (jrbnonstop.isSelected()) && (jrbround.isSelected()) && jrbeconomy.isSelected()){
            cost=k.Cairo("Tripss.txt")+30;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            }
            else if ((jrbminibus.isSelected()) &&(jComboBox3.getSelectedItem().equals("Cairo")) && (jrbonestop.isSelected()) && (jrbround.isSelected()) && jrbeconomy.isSelected()){
             cost=k.Cairo("Tripss.txt")+20;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            
            }
            else if ((jrbminibus.isSelected()) &&(jComboBox3.getSelectedItem().equals("Cairo")) && (jrbmanystop.isSelected()) && (jrbround.isSelected()) && jrbeconomy.isSelected()){
             cost=k.Cairo("Tripss.txt")+5;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            
            }
            
       else      if((jrbminibus.isSelected()) &&(jComboBox3.getSelectedItem().equals("Cairo")) && (jrbnonstop.isSelected()) && (jrbsingle.isSelected()) && jrbeconomy.isSelected()){
                cost=k.Cairo("Tripss.txt")+55;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            }
            else if ((jrbminibus.isSelected()) &&(jComboBox3.getSelectedItem().equals("Cairo")) && (jrbonestop.isSelected()) && (jrbsingle.isSelected()) && jrbcomfort.isSelected()){
             cost=k.Cairo("Tripss.txt")+65;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            
            }
            else if((jrbminibus.isSelected()) &&(jComboBox3.getSelectedItem().equals("Cairo")) && (jrbmanystop.isSelected()) && (jrbsingle.isSelected()) && jrbcomfort.isSelected()){
            cost=k.Cairo("Tripss.txt")+45;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            }
            
            else if((jrbminibus.isSelected()) &&(jComboBox3.getSelectedItem().equals("Cairo")) && (jrbnonstop.isSelected()) && (jrbround.isSelected()) && jrbcomfort.isSelected()){
            cost=k.Cairo("Tripss.txt")+40;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            }
            else if ((jrbminibus.isSelected()) &&(jComboBox3.getSelectedItem().equals("Cairo")) && (jrbonestop.isSelected()) && (jrbround.isSelected()) && jrbcomfort.isSelected()){
             cost=k.Cairo("Tripss.txt")+30;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            
            }
            else if ((jrbminibus.isSelected()) &&(jComboBox3.getSelectedItem().equals("Cairo")) && (jrbmanystop.isSelected()) && (jrbround.isSelected()) && jrbcomfort.isSelected()){
             cost=k.Cairo("Tripss.txt")+20;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            
            }
            
        } catch (IOException ex) {
            Logger.getLogger(customer.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            k.Lybia("Tripss.txt");
            if((jrbminibus.isSelected()) &&(jComboBox3.getSelectedItem().equals("Lybia")) && (jrbnonstop.isSelected()) && (jrbsingle.isSelected()) && jrbeconomy.isSelected()){
                cost=k.Lybia("Tripss.txt")+55;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            }
            else if ((jrbminibus.isSelected()) &&(jComboBox3.getSelectedItem().equals("Lybia")) && (jrbonestop.isSelected()) && (jrbsingle.isSelected()) && jrbeconomy.isSelected()){
             cost=k.Lybia("Tripss.txt")+45;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            
            }
            else if((jrbminibus.isSelected()) &&(jComboBox3.getSelectedItem().equals("Lybia")) && (jrbmanystop.isSelected()) && (jrbsingle.isSelected()) && jrbeconomy.isSelected()){
            cost=k.Lybia("Tripss.txt")+35;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            }
            
            else if((jrbminibus.isSelected()) &&(jComboBox3.getSelectedItem().equals("Lybia")) && (jrbnonstop.isSelected()) && (jrbround.isSelected()) && jrbeconomy.isSelected()){
            cost=k.Lybia("Tripss.txt")+30;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            }
            else if ((jrbminibus.isSelected()) &&(jComboBox3.getSelectedItem().equals("Lybia")) && (jrbonestop.isSelected()) && (jrbround.isSelected()) && jrbeconomy.isSelected()){
             cost=k.Lybia("Tripss.txt")+20;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            
            }
            else if ((jrbminibus.isSelected()) &&(jComboBox3.getSelectedItem().equals("Lybia")) && (jrbmanystop.isSelected()) && (jrbround.isSelected()) && jrbeconomy.isSelected()){
             cost=k.Lybia("Tripss.txt")+5;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            
            }
            
           else  if((jrbminibus.isSelected()) &&(jComboBox3.getSelectedItem().equals("Lybia")) && (jrbnonstop.isSelected()) && (jrbsingle.isSelected()) && jrbeconomy.isSelected()){
                cost=k.Lybia("Tripss.txt")+55;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            }
            else if ((jrbminibus.isSelected()) &&(jComboBox3.getSelectedItem().equals("Lybia")) && (jrbonestop.isSelected()) && (jrbsingle.isSelected()) && jrbcomfort.isSelected()){
             cost=k.Lybia("Tripss.txt")+65;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            
            }
            else if((jrbminibus.isSelected()) &&(jComboBox3.getSelectedItem().equals("Lybia")) && (jrbmanystop.isSelected()) && (jrbsingle.isSelected()) && jrbcomfort.isSelected()){
            cost=k.Lybia("Tripss.txt")+45;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            }
            
            else if((jrbminibus.isSelected()) &&(jComboBox3.getSelectedItem().equals("Lybia")) && (jrbnonstop.isSelected()) && (jrbround.isSelected()) && jrbcomfort.isSelected()){
            cost=k.Lybia("Tripss.txt")+40;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            }
            else if ((jrbminibus.isSelected()) &&(jComboBox3.getSelectedItem().equals("Lybia")) && (jrbonestop.isSelected()) && (jrbround.isSelected()) && jrbcomfort.isSelected()){
             cost=k.Lybia("Tripss.txt")+30;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            
            }
            else if ((jrbminibus.isSelected()) &&(jComboBox3.getSelectedItem().equals("Lybia")) && (jrbmanystop.isSelected()) && (jrbround.isSelected()) && jrbcomfort.isSelected()){
             cost=k.Lybia("Tripss.txt")+20;
                String sCost=String.format(" Egp%.2f " , cost);
                jLabel4.setText(sCost);
            
            }
            
        } catch (IOException ex) {
            Logger.getLogger(customer.class.getName()).log(Level.SEVERE, null, ex);
        }
                    try {
            k.Sharm("Tripss.txt");
            if((jrbminibus.isSelected()) &&(jComboBox3.getSelectedItem().equals("SharmElSheikh")) && (jrbnonstop.isSelected()) && (jrbsingle.isSelected()) && jrbeconomy.isSelected()){
                cost=k.Sharm("Tripss.txt")+55;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            }
            else if ((jrbminibus.isSelected()) &&(jComboBox3.getSelectedItem().equals("SharmElSheikh")) && (jrbonestop.isSelected()) && (jrbsingle.isSelected()) && jrbeconomy.isSelected()){
             cost=k.Sharm("Tripss.txt")+45;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            
            }
            else if((jrbminibus.isSelected()) &&(jComboBox3.getSelectedItem().equals("SharmElSheikh")) && (jrbmanystop.isSelected()) && (jrbsingle.isSelected()) && jrbeconomy.isSelected()){
            cost=k.Sharm("Tripss.txt")+35;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            }
            
            else if((jrbminibus.isSelected()) &&(jComboBox3.getSelectedItem().equals("SharmElSheikh")) && (jrbnonstop.isSelected()) && (jrbround.isSelected()) && jrbeconomy.isSelected()){
            cost=k.Sharm("Tripss.txt")+30;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            }
            else if ((jrbminibus.isSelected()) &&(jComboBox3.getSelectedItem().equals("SharmElSheikh")) && (jrbonestop.isSelected()) && (jrbround.isSelected()) && jrbeconomy.isSelected()){
             cost=k.Sharm("Tripss.txt")+20;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            
            }
            else if ((jrbminibus.isSelected()) &&(jComboBox3.getSelectedItem().equals("SharmElSheikh")) && (jrbmanystop.isSelected()) && (jrbround.isSelected()) && jrbeconomy.isSelected()){
             cost=k.Sharm("Tripss.txt")+5;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            
            }
            
           else  if((jrbminibus.isSelected()) &&(jComboBox3.getSelectedItem().equals("SharmElSheikh")) && (jrbnonstop.isSelected()) && (jrbsingle.isSelected()) && jrbeconomy.isSelected()){
                cost=k.Sharm("Tripss.txt")+55;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            }
            else if ((jrbminibus.isSelected()) &&(jComboBox3.getSelectedItem().equals("SharmElSheikh")) && (jrbonestop.isSelected()) && (jrbsingle.isSelected()) && jrbcomfort.isSelected()){
             cost=k.Sharm("Tripss.txt")+65;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            
            }
            else if((jrbminibus.isSelected()) &&(jComboBox3.getSelectedItem().equals("SharmElSheikh")) && (jrbmanystop.isSelected()) && (jrbsingle.isSelected()) && jrbcomfort.isSelected()){
            cost=k.Sharm("Tripss.txt")+45;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            }
            
            else if((jrbminibus.isSelected()) &&(jComboBox3.getSelectedItem().equals("SharmElSheikh")) && (jrbnonstop.isSelected()) && (jrbround.isSelected()) && jrbcomfort.isSelected()){
            cost=k.Sharm("Tripss.txt")+40;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            }
            else if ((jrbminibus.isSelected()) &&(jComboBox3.getSelectedItem().equals("SharmElSheikh")) && (jrbonestop.isSelected()) && (jrbround.isSelected()) && jrbcomfort.isSelected()){
             cost=k.Sharm("Tripss.txt")+30;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            
            }
            else if ((jrbminibus.isSelected()) &&(jComboBox3.getSelectedItem().equals("SharmElSheikh")) && (jrbmanystop.isSelected()) && (jrbround.isSelected()) && jrbcomfort.isSelected()){
             cost=k.Sharm("Tripss.txt")+20;
                String sCost=String.format(" Egp%.2f " , cost);
                jLabel4.setText(sCost);
            
            }
            
        } catch (IOException ex) {
            Logger.getLogger(customer.class.getName()).log(Level.SEVERE, null, ex);
        }
                    
                    try {
            k.Ismailia("Tripss.txt");
            if((jrbminibus.isSelected()) &&(jComboBox3.getSelectedItem().equals("Ismailia")) && (jrbnonstop.isSelected()) && (jrbsingle.isSelected()) && jrbeconomy.isSelected()){
                cost=k.Ismailia("Tripss.txt")+55;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            }
            else if ((jrbminibus.isSelected()) &&(jComboBox3.getSelectedItem().equals("Ismailia")) && (jrbonestop.isSelected()) && (jrbsingle.isSelected()) && jrbeconomy.isSelected()){
             cost=k.Ismailia("Tripss.txt")+45;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            
            }
            else if((jrbminibus.isSelected()) &&(jComboBox3.getSelectedItem().equals("Ismailia")) && (jrbmanystop.isSelected()) && (jrbsingle.isSelected()) && jrbeconomy.isSelected()){
            cost=k.Ismailia("Tripss.txt")+35;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            }
            
            else if((jrbminibus.isSelected()) &&(jComboBox3.getSelectedItem().equals("Ismailia")) && (jrbnonstop.isSelected()) && (jrbround.isSelected()) && jrbeconomy.isSelected()){
            cost=k.Ismailia("Tripss.txt")+30;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            }
            else if ((jrbminibus.isSelected()) &&(jComboBox3.getSelectedItem().equals("Ismailia")) && (jrbonestop.isSelected()) && (jrbround.isSelected()) && jrbeconomy.isSelected()){
             cost=k.Ismailia("Tripss.txt")+20;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            
            }
            else if ((jrbminibus.isSelected()) &&(jComboBox3.getSelectedItem().equals("Ismailia")) && (jrbmanystop.isSelected()) && (jrbround.isSelected()) && jrbeconomy.isSelected()){
             cost=k.Ismailia("Tripss.txt")+5;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            
            }
            
           else  if((jrbminibus.isSelected()) &&(jComboBox3.getSelectedItem().equals("Ismailia")) && (jrbnonstop.isSelected()) && (jrbsingle.isSelected()) && jrbeconomy.isSelected()){
                cost=k.Ismailia("Tripss.txt")+55;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            }
            else if ((jrbminibus.isSelected()) &&(jComboBox3.getSelectedItem().equals("Ismailia")) && (jrbonestop.isSelected()) && (jrbsingle.isSelected()) && jrbcomfort.isSelected()){
             cost=k.Ismailia("Tripss.txt")+65;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            
            }
            else if((jrbminibus.isSelected()) &&(jComboBox3.getSelectedItem().equals("Ismailia")) && (jrbmanystop.isSelected()) && (jrbsingle.isSelected()) && jrbcomfort.isSelected()){
            cost=k.Ismailia("Tripss.txt")+45;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            }
            
            else if((jrbminibus.isSelected()) &&(jComboBox3.getSelectedItem().equals("Ismailia")) && (jrbnonstop.isSelected()) && (jrbround.isSelected()) && jrbcomfort.isSelected()){
            cost=k.Ismailia("Tripss.txt")+40;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            }
            else if ((jrbminibus.isSelected()) &&(jComboBox3.getSelectedItem().equals("Ismailia")) && (jrbonestop.isSelected()) && (jrbround.isSelected()) && jrbcomfort.isSelected()){
             cost=k.Ismailia("Tripss.txt")+30;
                String sCost=String.format("Egp%.2f ", cost);
                jLabel4.setText(sCost);
            
            }
            else if ((jrbminibus.isSelected()) &&(jComboBox3.getSelectedItem().equals("Ismailia")) && (jrbmanystop.isSelected()) && (jrbround.isSelected()) && jrbcomfort.isSelected()){
             cost=k.Ismailia("Tripss.txt")+20;
                String sCost=String.format(" Egp%.2f " , cost);
                jLabel4.setText(sCost);
            
            }
            
        } catch (IOException ex) {
            Logger.getLogger(customer.class.getName()).log(Level.SEVERE, null, ex);
        }
                    
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        
        
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  String b=jButton5.getText();
   try {
            FileWriter writer = new FileWriter("Booking.txt",true);
            writer.write((String) (jComboBox3.getSelectedItem())+ " ");
            
            writer.write((String) (jLabel4.getText()) );
            writer.write(System.getProperty("line.separator"));
   writer.close();
             JOptionPane.showMessageDialog(rootPane,"Booked"); 
   
   } catch (IOException ex) {
        Logger.getLogger(customer.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jrbbusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbbusActionPerformed
      Bus b=new Bus();
      b.Date();
    }//GEN-LAST:event_jrbbusActionPerformed

    private void jrbminibusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbminibusActionPerformed
        MiniBus c=new MiniBus();
        
    }//GEN-LAST:event_jrbminibusActionPerformed

    private void jrblimousineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrblimousineActionPerformed
        Limousine l=new Limousine();
        
    }//GEN-LAST:event_jrblimousineActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new customer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton jrbbus;
    private javax.swing.JRadioButton jrbcomfort;
    private javax.swing.JRadioButton jrbeconomy;
    private javax.swing.JRadioButton jrblimousine;
    private javax.swing.JRadioButton jrbmanystop;
    private javax.swing.JRadioButton jrbminibus;
    private javax.swing.JRadioButton jrbnonstop;
    private javax.swing.JRadioButton jrbonestop;
    private javax.swing.JRadioButton jrbround;
    private javax.swing.JRadioButton jrbsingle;
    // End of variables declaration//GEN-END:variables
}
